title: Humans of SUTD
email: humans@sutd.edu.sg
description: We are the Humans of SUTD, a dedicated team of researchers passionate about behavioral experiments. We love to share about the nitty-gritty of designing cool 😎 experiments and hope you will find answers to your research questions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: humansofsutd

minima:
  date_format: "%B %d, %Y"

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

assets:
  compress:
    css: true
    js: true
  digest: true
  sources:
    - assets/css
    - assets/fonts
    - assets/js
    - assets/images
